### ISSUE TITLE
libstirshaken in C++ getting undefined reference to `stir_shaken_do_init

### ISSUE THREAD

**Issue by baloian** [signalwire/libstirshaken#110]
Hi

I am trying to use `libstirshaken` in C++ code and getting the following error:
```bash
stirshaken.cpp:(.text.startup+0x5d): undefined reference to `stir_shaken_do_init(stir_shaken_context_s*, char const*, char const*, int)'
```

The project is based on `CMake` and I added `-lstirshaken` option.

Any suggestion what can I do?

**Comment by baloian** [comment]
@crienzo, this issue is still valid and just wondering if this is possible. Looks like, based on Makefile, I have to compile the library source files as well. Am I correct or missing something?

**Comment by crienzo** [comment]
Merged your PR

**Comment by baloian** [comment]
Thank you. I am closing the issue.
