### ISSUE TITLE
Help link on main page is inoperative

### ISSUE THREAD

**Issue by mrtrev** [signalwire/libstirshaken#127]
At the bottom of https://github.com/signalwire/libstirshaken it says

> Help
> Any questions? Please let us know at: https://signalwire-community.slack.com/

However this is not a publicly accessible channel.

When attempting to register for access an @signalwire.com email address is required.

It seems silly to list an staff-only resource for a place to ask questions.  This should be replaced with a channel that is accessible to any user of this library.

**Comment by mjerris** [comment]
you don’t need a signalwire.com email address.  this is a page from slack that offers the different options to log in or create an account

**Comment by mrtrev** [comment]
I can confirm that it will not allow me to use my email address.

If I enter my whole address, it errors back

> Please only enter the part before the @ sign in your email address.

I also cannot change the @signalwire.com portion that is already there.

Please advise how to complete this process without a signalwire.com address and perhaps add that to the main page.

**Comment by mrtrev** [comment]
> Don’t have an @signalwire.com email address?
> Contact the workspace administrator at SignalWire Community for an invitation.

Or maybe add the contact information for the workspace administrator?
