### ISSUE TITLE
How to ask a question using the Slack link

### ISSUE THREAD

**Issue by mrtrev** [signalwire/libstirshaken#128]
Hello,

I am incapable of gaining access to the channel referenced under the Help section of the documentation.  As this bug reporting is the only place I can find a way to get attention, please point out where I am going wrong here.

On the bottom of https://github.com/signalwire/libstirshaken it says
> Help
> Any questions? Please let us know at: https://signalwire-community.slack.com/

Steps to reproduce:

1. Click the link which is https://signalwire-community.slack.com/

![image](https://user-images.githubusercontent.com/27308661/208264650-3281b83d-4815-47a9-a07c-b6709b0bf4d7.png)

2. Click the button on the top right to create an account

![image](https://user-images.githubusercontent.com/27308661/208264686-a7bf7968-b4ff-4e10-9488-6af6dcc1dc36.png)

3. I don't have an @signalwire.com email account and I don't have contact information for the workspace administrator.  I cannot edit or remove the @signalwire.com portion of the address.  I don't know how to move forward from here.

I have previously created #127 but it was closed without any clarification.

I had hoped that the instructions would have been clarified but apparently this is a me problem, not a documentation problem, so please do enlighten me on how the public can use that communications channel to ask a question.

**Comment by andywolk** [comment]
Please try https://signalwire.community/

**Comment by mrtrev** [comment]
Thanks.  That one works.  Perhaps update the document with this link?

**Comment by andywolk** [comment]
You can make a PR, we will review.
