### ISSUE TITLE
Add command to stirshaken tool for complete jwt check (with implicit http cert downloading)

### ISSUE THREAD

**Issue by spinlockirqsave** [signalwire/libstirshaken#36]
Currently there's jwt-check command for checking jwt against public key, but function taking only JWT as input will also be useful.
This would download the cert during verification process, so it must basically be wrapped  stir_shaken_jwt_verify_and_check_x509_cert_path().

**Comment by piotr-gregor** [comment]
Added in https://github.com/signalwire/libstirshaken/pull/41
