### ISSUE TITLE
Cert caching

### ISSUE THREAD

**Issue by spinlockirqsave** [signalwire/libstirshaken#59]
As our friend - Kamailio's Daniel-Constantin Mierla suggested, possibility to cache STI certs instead of downloading them each time PASSporT verification is performed will be useful in some cases. Add callback to verification procedure enabling the caller to  supply previously cached cert or request HTTP download.

**Comment by piotr-gregor** [comment]
Added in commit commit baa88b53b11ab4ceb3efe69d1c0b89d5bacc7ef2
Author: Piotr Gregor <piotr@dataandsignal.com>
Date:   Thu Sep 17 22:56:23 2020 +0000

    Support certificate caching
